name: Continuos Integration / Continuos Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  CI:
    name: Continous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run in automatic mode
        run: |
          chmod +x chumbi-image-downloader.sh
          ./chumbi-image-downloader.sh auto

  pre-release:
    name: Continuous Deployment
    needs: CI
    runs-on: ubuntu-latest
    steps:

      - name: Create Archive Prerelease
        uses: papeloto/action-zip@v1
        with:
          files: chumbi-image-downloader.sh chumbi-sticker-list.txt chumbi-emoji-list.txt README.md LICENSE
          dest: '${{ github.repository }}-${{ github.hash }}.zip'

      - name: Upload Prerelease
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          file: '${{ github.repository }}-${{ github.hash }}.zip'
          tag: ${{ github.hash }}
          asset_name: '${{ github.repository }}-{{ github.hash }}-prerelase.zip'
          overwrite: true
          prerelease: true
