name: Continuos Integration / Continuos Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  CI:
    name: Continous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run in automatic mode
        run: |
          chmod +x chumbi-image-downloader.sh
          ./chumbi-image-downloader.sh auto

  pre-release:
    name: Continuous Deployment
    needs: CI
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Create Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: '${{ github.repository }}-${{ github.hash }}.zip'
          exclusions: '*.git*'

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ github.repository }}-${{ github.hash }}.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Automatic Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Release"
          files: |
            LICENSE
            *.sh
            *.txt
            *.zip
