name: Zip Files

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: LICENSE README.md chumbi-emoji-list.txt chumbi-image-downloader.sh chumbi-sticker-list.txt
          dest: ${{ github.repository }}-${{ github.sha | cut -c1-8 }}.zip
